### ISSUE TITLE
Release v1.0 checklist

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/mithril.web#7]
- [x] Add titles to all pages and translate them (title, og:title).
- [x] Check Readme.md for all description and env variables
- [x] Check docker hub page for env variable description
- [x] Check all dependencies and components and remove unused
- [x] Check server side rendering
